version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 1
    rebase-strategy: "auto"
    allow:
      - dependency-name: "yt-dlp"
      - dependency-name: "yt-dlp-ejs"
    groups:
      youtube-downloader:
        patterns:
          - "yt-dlp"
          - "yt-dlp-ejs"
