#!/usr/bin/env python3
"""
Текстовые утилиты — очистка, нормализация, title case.
Извлечено из bot.py строки 1587–1845.
"""
import re
from core.core_utils import time_to_seconds  # разрыв цикла: ранее был lazy import из json_parser

BAD_META_PATTERNS = [
    # Cocoon / AI / meta-boilerplate — только явный мусор
    r"cocoon\s*ai\s*summary",
    r"\bcocoon\b",
    r"content\s*summary",
    r"ai\s+summary",
    r"summary\s+by",
    r"auto.?generated\s+summary",
    r"auto.?generated",
    r"^generated\s+by",
    r"^powered\s+by",
    r"^content\s+by",
    r"\bbyline\b",
    # Дата-подписи вида "March 15 at 18:55"
    r"[\s\u2022\-]*\w+\s+\d{1,2}\s+at\s+\d{1,2}:\d{2}",
    r"march\s+\d{1,2}\s+at\s+\d{1,2}:\d{2}",
    r"(?:january|february|march|april|may|june|july|august|september|october|november|december)\s+\d{1,2},?\s*\d{4}",
    # Русские мета-фразы — только строгие якоря
    r"^статья\s+(содержит|описывает|рассматривает|анализирует|представляет)",
    r"^статья\s+представляет\s+собой",
    r"^this\s+(video|article|sermon|lecture)\s+",
    r"^в\s+этом\s+(видео|ролике)\s+",
    r"текст\s+подготовлен\s+с\s+помощью",
    r"подготовлен[оа]?\s+с\s+помощью\s+(gemini|ai|ии)",
]

# Паттерны для инлайн-замены (встречаются внутри строки, не только в начале)
_INLINE_SCRUB_PATTERNS = [
    # Только строки-маркеры которые встречаются внутри текста как вставки
    r"cocoon\s*ai\s*summary",
    r"\bcocoon\b",
    r"content\s*summary",
    r"ai\s+summary",
    r"summary by[^.]*",
    r"auto.?generated[^.]*",
    r"generated by[^.]*",
    r"powered by[^.]*",
    r"\bbyline\b",
    r"\w+\s+\d{1,2}\s+at\s+\d{1,2}:\d{2}",    # "March 7 at 5:11"
    r"текст\s+подготовлен\s+с\s+помощью[^.]*",
    r"подготовлен[оа]?\s+с\s+помощью\s+gemini\s*ai[^.]*",
]


def _scrub_inline(text: str) -> str:
    """Удаляет мусорные AI/meta-фразы встречающиеся внутри строки.
    НЕ трогает пунктуацию, края строки и смысловые пробелы —
    чтобы не ломать богословский текст, scripture, переводческие блоки."""
    if not text:
        return text
    for pat in _INLINE_SCRUB_PATTERNS:
        text = re.sub(pat, "", text, flags=re.IGNORECASE)
    # Схлопываем только множественные пробелы/табы внутри строки
    text = re.sub(r"[ \t]{2,}", " ", text)
    return text

def _clean_meta_line(s: str) -> str:
    """Берёт первую осмысленную строку, отфильтровывая мусорные метки платформ."""
    s = (s or "").strip()
    if not s:
        return ""
    lines = [ln.strip() for ln in s.splitlines() if ln.strip()]
    for ln in lines:
        low = ln.lower()
        if any(re.search(p, low) for p in BAD_META_PATTERNS):
            continue
        return ln
    return ""

def _clean_field(s: str) -> str:
    """Очищает произвольное текстовое поле — возвращает пустую строку если мусор."""
    s = (s or "").strip()
    if not s:
        return ""
    if any(re.search(p, s.lower(), re.IGNORECASE) for p in BAD_META_PATTERNS):
        return ""
    if s[-1] not in '.!?…':
        # #82: не добавляем точку если строка заканчивается на .) — напр. «агнец (лат.)»
        if not re.search(r'\.\)\s*$', s):
            s = s + '.'
    return s

def _clean_list(lst: list) -> list:
    """Фильтрует список строк, убирая мусорные элементы."""
    return [_clean_field(str(item)) for item in (lst or []) if _clean_field(str(item))]


def _strip_meta_lines(text: str) -> str:
    """Удаляет строки, соответствующие BAD_META_PATTERNS, возвращает чистый текст."""
    if not text:
        return ""
    clean_lines = []
    for ln in text.splitlines():
        stripped = ln.strip()
        if not stripped:
            clean_lines.append(ln)
            continue
        if any(re.search(p, stripped, re.IGNORECASE) for p in BAD_META_PATTERNS):
            continue
        clean_lines.append(ln)
    return "\n".join(clean_lines).strip()


def _has_dirty_meta(text: str) -> bool:
    """True если в тексте есть хотя бы одна мусорная строка."""
    for ln in (text or "").splitlines():
        if ln.strip() and any(re.search(p, ln.strip(), re.IGNORECASE) for p in BAD_META_PATTERNS):
            return True
    return False


def is_meta_garbage(s: str) -> bool:
    """True если строка целиком является мусором (summary/byline/cocoon и т.п.)."""
    s = (s or "").strip()
    if not s:
        return True
    return any(re.search(p, s, re.IGNORECASE) for p in BAD_META_PATTERNS)


def normalize_author_name(s: str) -> str:
    """Нормализует имя автора: убирает мусор, длинные тире → дефис, схлопывает пробелы."""
    s = _strip_meta_lines((s or "").strip())
    if not s or is_meta_garbage(s):
        return ""
    s = re.sub(r"[—–]", "-", s)
    s = re.sub(r"\s{2,}", " ", s).strip()
    s = s.strip("-").strip()
    return s


def normalize_title_text(s: str) -> str:
    """Нормализует заголовок: убирает ведущий номер серии, имя автора в скобках, лишние разделители."""
    s = _strip_meta_lines((s or "").strip())
    if not s or is_meta_garbage(s):
        return ""

    s = re.sub(r"^\d+\s*[|:]\s*", "", s)
    s = re.sub(r"^№\d+\s*[|:\-]?\s*", "", s)
    s = re.sub(r"^[Ss]\d+[Ee]\d+\s*[|:\-]?\s*", "", s)
    s = re.sub(r"^[Ee]pisode\s+\d+\s*[|:\-]?\s*", "", s, flags=re.IGNORECASE)

    m = re.search(r"\(([^)]{2,50})\)\s*$", s)
    if m:
        candidate = m.group(1).strip()
        words = candidate.split()
        meaningful_words = [w for w in words if w]
        word_count = len(meaningful_words)
        if word_count in (2, 3, 4) and meaningful_words:
            _NOT_NAME_WORDS = {
                "часть", "серия", "том", "выпуск", "новый", "старый",
                "ветхий", "завет", "глава", "книга", "версия",
                "old", "new", "part", "vol", "series", "chapter",
                "version", "official", "audio", "video", "live",
                "full", "hd", "original", "remix", "edit",
            }
            looks_like_name = all(
                w[0].isupper()
                and not any(c.isdigit() for c in w)
                and w.lower() not in _NOT_NAME_WORDS
                for w in meaningful_words
            )
            if looks_like_name:
                s = re.sub(r"\s*\([^)]{2,50}\)\s*$", "", s)

    s = re.sub(r"[\s|]+$", "", s).strip()
    s = re.sub(r"\s{2,}", " ", s).strip()
    s = re.sub(r"(?<!\.)\.(?!\.)$", "", s).strip()

    return s



# Слова/акронимы которые нельзя трогать при title case
_PRESERVE_CASE: frozenset = frozenset({
    # Версии Библии и богословские аббревиатуры
    "ESV", "KJV", "NASB", "NIV", "LSB", "NLT", "CSB", "NKJV", "RSV", "NET",
    "NRSV", "LEB", "ASV", "LBCF", "LBCF1689", "WCF", "TULIP",
    # Форматы
    "Q&A", "QA",
    # Технические/бренды
    "YouTube", "RuTube", "VK", "iPhone", "iPad",
    # Языки оригинала
    "NA28", "BHS", "LXX",
})


def title_case_fragment(s: str) -> str:
    """
    Title Case для названий фрагментов (Shorts / Clips).
    Каждое слово с заглавной буквы, кроме коротких предлогов/союзов
    в середине фразы. Акронимы и слова из _PRESERVE_CASE не трогаются.
    """
    if not s:
        return s

    _LOWER_MID = {
        "в", "на", "за", "из", "по", "к", "с", "о", "у", "до", "об", "от",
        "под", "над", "при", "про", "без", "для", "через", "между",
        "и", "а", "но", "или", "да", "не", "ни", "же", "ли", "бы",
        "a", "an", "the", "of", "in", "on", "at", "to", "for", "and",
        "or", "but", "nor", "as", "by", "up",
    }

    def _capitalize_first_letter(word: str) -> str:
        """Капитализирует первую БУКВУ в слове, пропуская ведущую пунктуацию."""
        for i, ch in enumerate(word):
            if ch.isalpha():
                return word[:i] + ch.upper() + word[i + 1:]
        return word

    words = s.split()
    result = []
    for i, word in enumerate(words):
        if word in _PRESERVE_CASE or word.upper() in _PRESERVE_CASE:
            canonical = next((w for w in _PRESERVE_CASE if w.upper() == word.upper()), word)
            result.append(canonical)

        elif len(word) >= 2 and word.isupper() and word.isalpha():
            result.append(word)

        elif i == 0 or i == len(words) - 1:
            result.append(_capitalize_first_letter(word))

        elif word.lower() in _LOWER_MID:
            result.append(word.lower())

        else:
            result.append(_capitalize_first_letter(word))

    return " ".join(result)

def _filter_times_str(times_str: str, duration: int) -> str:
    """
    Фильтрует строку с таймкодами: оставляет только те, что не превышают duration.
    Автокоррекция: H:MM:SS → MM:SS для видео короче часа (типичная ошибка Gemini).
    """
    if not times_str or not duration:
        return times_str or ""
    times_str = re.sub(r"[•·]", ", ", times_str)
    tokens = [t.strip('.,;:!? ') for t in re.split(r"[,\s]+", times_str) if t.strip()]
    good: list[str] = []
    for token in tokens:
        secs = time_to_seconds(token)
        if secs is None:
            continue
        if duration < 3600 and secs > duration:
            parts = token.split(":")
            if len(parts) == 3:
                corrected = f"{parts[1]}:{parts[2]}"
                corrected_secs = time_to_seconds(corrected)
                if corrected_secs is not None and corrected_secs <= duration:
                    good.append(corrected)
                    continue
            continue
        if secs <= duration:
            good.append(token)
    return ", ".join(good)


