from pathlib import Path

path = Path(__file__).with_name("apply_audit_hardening_once.py")
text = path.read_text(encoding="utf-8")
marker = 'print("AUDIT_HARDENING_PATCH_APPLIED")\n'
if text.count(marker) != 1:
    raise RuntimeError("audit patcher terminal marker is not unique")

extra = r'''# 9) Feed source metadata duration into acquisition immediately, not only the
# later render-source validator.
replace_once(
    "pipelines/shorts_factory.py",
    '''        mp3_path = await _download_factory_audio(\n            url,\n            media_id,\n            status_msg=status_msg,\n        )\n''',
    '''        mp3_path = await _download_factory_audio(\n            url,\n            media_id,\n            status_msg=status_msg,\n            expected_duration=float(duration),\n        )\n''',
)
replace_once(
    "pipelines/shorts_factory.py",
    '''                download_video_for_shorts(url, media_id, workdir=workdir),\n''',
    '''                download_video_for_shorts(\n                    url,\n                    media_id,\n                    workdir=workdir,\n                    expected_duration=float(duration),\n                ),\n''',
)

# 10) Model fallback is gone, so remove the old process-global bookkeeping
# rather than leaving an inert ambient flag behind.
replace_once(
    "services/telegraph_pages.py",
    '''# Backward-compatible marker consumed by main_pipeline. Semantic Telegraph\n# generation is now strict-primary, so this remains False: an unavailable\n# primary model omits the optional section instead of downgrading to Lite.\n_gemini_last_was_fallback: bool = False\n''',
    "",
)
replace_once(
    "pipelines/main_pipeline.py",
    '''# AUDIT R39: импортируем МОДУЛЬ, а не значение флага — иначе имя связывалось с\n# False на момент импорта и переустановки telegraph_pages._gemini_last_was_fallback\n# его не меняли (маркер lite-модели в подписи был мёртвым кодом).\nimport services.telegraph_pages as _tp_module\n''',
    "",
)
replace_once(
    "pipelines/main_pipeline.py",
    '''        # PATCH-FIX: surface lite-model fallback in caption so user knows quality may be reduced\n        if _tp_module._gemini_last_was_fallback:   # AUDIT R39: живое значение из модуля\n            _ai_caption_base = {**(_ai_caption_base or ai_data), "_gemini_was_fallback": True}\n\n''',
    "",
)
replace_once(
    "converters/caption.py",
    '''    # A fallback in Telegraph pages does not mean the primary audio analysis was\n    # generated by the reserve model. Keep the public warning stage-accurate.\n    if ai_data and ai_data.get("_gemini_was_fallback"):\n        parts.append("")\n        parts.append("⚡ Один из дополнительных разделов создан на резервной модели; основной разбор и таймкоды могли быть созданы основной моделью.")\n\n''',
    "",
)

# Keep diagnostics truthful now that audio semantic fallback is impossible.
replace_once(
    "services/gemini_analyze.py",
    '''    # AUDIT FIX MULTI-MODEL: fallback по качеству (для редких но мощных запросов)\n    # Юзкейс: 1-5 видео/день, главное — качество анализа\n    _user_model = GEMINI_MODEL\n    _models_to_try = _audio_fallback_models(_user_model)\n    logger.info(\n        "Gemini audio models (quality-first; AUDIO_ANALYSIS_FALLBACK_MODE=%s): %s",\n        (os.getenv("AUDIO_ANALYSIS_FALLBACK_MODE", "strict") or "strict"),\n        _models_to_try,\n    )\n''',
    '''    _user_model = GEMINI_MODEL\n    _models_to_try = _audio_fallback_models(_user_model)\n    logger.info("Gemini audio model (strict no-downgrade): %s", _models_to_try)\n''',
)

# 11) The one-time launcher migration removes WPC, and startup additionally
# fails closed if the legacy browser provider is ever manually reintroduced.
replace_once(
    "services/youtube_po_token_runtime.py",
    'BGUTIL_DISTRIBUTION = "bgutil-ytdlp-pot-provider"\n',
    'BGUTIL_DISTRIBUTION = "bgutil-ytdlp-pot-provider"\nLEGACY_WPC_DISTRIBUTION = "yt-dlp-getpot-wpc"\n',
)
replace_once(
    "services/youtube_po_token_runtime.py",
    '''def _distribution_version(name: str) -> str:\n''',
    '''def _require_no_legacy_browser_provider() -> None:\n    try:\n        legacy_version = metadata.version(LEGACY_WPC_DISTRIBUTION)\n    except metadata.PackageNotFoundError:\n        return\n    raise YouTubePoTokenRuntimeError(\n        "Обнаружен устаревший browser-based PO Token provider "\n        f"{LEGACY_WPC_DISTRIBUTION} {legacy_version}. Запусти Start Bot.bat: "\n        "он удалит WPC/nodriver; Chrome fallback в production запрещён."\n    )\n\n\ndef _distribution_version(name: str) -> str:\n''',
)
replace_once(
    "services/youtube_po_token_runtime.py",
    '''    provider_version = _distribution_version(BGUTIL_DISTRIBUTION)\n''',
    '''    _require_no_legacy_browser_provider()\n    provider_version = _distribution_version(BGUTIL_DISTRIBUTION)\n''',
)
replace_once(
    "services/youtube_po_token_runtime.py",
    '''    "DEFAULT_PROVIDER_HOME",\n''',
    '''    "DEFAULT_PROVIDER_HOME",\n    "LEGACY_WPC_DISTRIBUTION",\n''',
)

write_file(
    "tests/test_semantic_no_downgrade.py",
    '''from __future__ import annotations\n\nimport inspect\nfrom pathlib import Path\n\nfrom services import gemini_analyze\nfrom services import telegraph_pages\n\n\ndef test_primary_audio_emergency_env_cannot_enable_lite(monkeypatch):\n    monkeypatch.setenv("AUDIO_ANALYSIS_FALLBACK_MODE", "lite")\n    assert gemini_analyze._audio_fallback_models("gemini-3.7-flash") == [\n        "gemini-3.7-flash"\n    ]\n\n\ndef test_telegraph_semantic_fallback_is_disabled_by_default():\n    parameter = inspect.signature(telegraph_pages._gemini_text_request).parameters[\n        "allow_model_fallback"\n    ]\n    assert parameter.default is False\n\n\ndef test_old_process_global_fallback_bookkeeping_is_removed():\n    telegraph = Path("services/telegraph_pages.py").read_text(encoding="utf-8")\n    pipeline = Path("pipelines/main_pipeline.py").read_text(encoding="utf-8")\n    caption = Path("converters/caption.py").read_text(encoding="utf-8")\n    assert "_gemini_last_was_fallback" not in telegraph\n    assert "_gemini_last_was_fallback" not in pipeline\n    assert "_gemini_was_fallback" not in caption\n''',
)

write_file(
    "tests/test_factory_acquisition_duration_contract.py",
    '''from __future__ import annotations\n\nimport ast\nfrom pathlib import Path\n\n\ndef _calls_in_process_factory():\n    tree = ast.parse(Path("pipelines/shorts_factory.py").read_text(encoding="utf-8"))\n    process = next(\n        node for node in tree.body\n        if isinstance(node, (ast.AsyncFunctionDef, ast.FunctionDef))\n        and node.name == "process_shorts_factory"\n    )\n    return [node for node in ast.walk(process) if isinstance(node, ast.Call)]\n\n\ndef _name(call: ast.Call) -> str:\n    if isinstance(call.func, ast.Name):\n        return call.func.id\n    return ""\n\n\ndef test_factory_audio_and_video_acquisition_receive_expected_duration():\n    calls = _calls_in_process_factory()\n    for target in ("_download_factory_audio", "download_video_for_shorts"):\n        matching = [call for call in calls if _name(call) == target]\n        assert matching, target\n        assert all(\n            any(keyword.arg == "expected_duration" for keyword in call.keywords)\n            for call in matching\n        ), target\n''',
)

# Extend PO tests with a runtime rejection of a manually reintroduced WPC plugin.
replace_once(
    "tests/test_youtube_po_token_runtime.py",
    '''def test_old_wpc_browser_stack_is_not_a_dependency() -> None:\n''',
    '''def test_runtime_rejects_reintroduced_wpc_provider(monkeypatch):\n    real_version = po.metadata.version\n\n    def fake_version(name: str):\n        if name == po.LEGACY_WPC_DISTRIBUTION:\n            return "1.1.2"\n        return real_version(name)\n\n    monkeypatch.setattr(po.metadata, "version", fake_version)\n    with pytest.raises(po.YouTubePoTokenRuntimeError, match="browser-based"):\n        po._require_no_legacy_browser_provider()\n\n\ndef test_old_wpc_browser_stack_is_not_a_dependency() -> None:\n''',
)

'''

path.write_text(text.replace(marker, extra + marker, 1), encoding="utf-8")
print("AUDIT_PATCHER_EXTENDED")
